### ISSUE TITLE
Why lucene doc id changes after updating or merging?

### ISSUE THREAD

**Issue by visionarywind** [apache/lucene#1048]
### Description

As I know, lucene doc is a internal docId, it cannot be used as an external id.  
Why is it designed like this ?
Could it be designed to be constant ?
Thank you.

**Comment by dweiss** [comment]
If you need constant IDs, use a stored document field. IDs are internal because they are used for per-segment document ordering and once segments are merged, any previous document IDs (they're actually an ordinal sequence) are discarded. The naming "ID" may be confusing - it's not a "global" identifier, it is only unique within a segment.
