### ISSUE TITLE
Remove IndexSearcher#search(Query,Collector) in favor of IndexSearcher#search(Query,CollectorManager) [LUCENE-10002]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11041]
It's a bit trappy that you can create an IndexSearcher with an executor, but that it would always search on the caller thread when calling `IndexSearcher#search(Query,Collector)`.

 Let's remove `IndexSearcher#search(Query,Collector)`, point our users to `IndexSearcher#search(Query,CollectorManager)` instead, and change factory methods of our main collectors (e.g. `TopScoreDocCollector#create`) to return a `CollectorManager` instead of a `Collector`?

---
Migrated from [LUCENE-10002](https://issues.apache.org/jira/browse/LUCENE-10002) by Adrien Grand (@jpountz), updated Apr 06 2022
Pull requests: https://github.com/apache/lucene/pull/240

**Comment by wardle** [comment]
Hi all. There is a small overhead with using CollectorManager over Collector. In my own usage, I have a read-only index which uses only a single slice, and I've chosen not to provide an executor service because my usage uses lots of cores for concurrent requests.

Consequently, it seems to be that this is more of an issue of documentation, and best practices. Additional usage information in IndexSearcher#search to point users to use a CollectorManager might well suffice, and prevent what is presumably a concern about incorrect usage, while permitting users who know the nature of their index, and their usage patterns, to leverage the APIs as they need. 

Clearly, it is trivial to use CollectorManager and wrap my existing (custom) Collector, but it is an unnecessary overhead, albeit a very small one, but at the cost of losing backwards compatibility and with little gain as fundamentally both could co-exist without complication, but documentation steering most users to prefer CollectorManager.

**Comment by javanna** [comment]
Only the actual removal of the deprecated search(Query, Collector) is left to do. That is tracked by #12892 hence this issue can be closed/
