### ISSUE TITLE
configuration items of the alg file are adapted to the 9.0 branch [LUCENE-10100]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11138]
Some configuration items of the alg file are no longer applicable, modified to adapt to the 9.0 branch.

---
Migrated from [LUCENE-10100](https://issues.apache.org/jira/browse/LUCENE-10100) by xiaoshi (@xiaoshi2013), updated Oct 18 2021
Pull requests: https://github.com/apache/lucene/pull/301

**Comment by mikemccand** [comment]
Merged to 10.0 and 9.9.0.  Thanks @xiaoshi2013!

**Comment by ChrisHegarty** [comment]
Hi,

I'd like to ask a clarifying question as part of the _9.9.0_ release manager duties, since this currently-unresolved issue is associated with Milestone 9.9.0.

Is more work planned, or should this issue be closed? It's fine either way, I just want to ensure that we are clear about the targeted release, if any.

**Comment by mikemccand** [comment]
Ahh thanks @ChrisHegarty -- no more work for this issue.
