### ISSUE TITLE
Add an equivalent of ant's stage-maven-artifacts for the release wizard [LUCENE-10293]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11329]
Currently the RC Maven artifacts cannot be easily moved to Nexus. Devise a way to do it from gradle (either as a bundle ZIP or directly, the way it was done before).

---
Migrated from [LUCENE-10293](https://issues.apache.org/jira/browse/LUCENE-10293) by Dawid Weiss (@dweiss), updated Apr 14 2022
Linked issues:
 - #10910

**Comment by dweiss** [comment]
I like what @HoustonPutman did on Solr side (using Nexus REST API directly). I think I'll take a stab at writing it in Java or groovy but otherwise it's a lot of progress over in that script!

Also, let's stick to the separate "maven" folder in the release. I was very tempted to move it over to the staging repository but it has too many moving parts... 

I'll handle this over the next few days - hopefully for the next release!

**Comment by dweiss** [comment]
Patch implemented in #11947
