### ISSUE TITLE
Relax the maximum dirtiness for stored fields and term vectors? [LUCENE-10556]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#11592]
Stored fields and term vectors compress data and have merge-time optimizations to copy compressed data directly instead of decompressing and recompressing over and over again. However, sometimes incomplete blocks get carried over (typically the last block of a flushed segment) and so these file formats keep track of how "dirty" their current blocks are to know whether stored fields / term vectors for a segment should be re-compressed.

Currently the logic is to recompress if more than 1% of the blocks are incomplete, or if the total number of missing documents across incomplete blocks is more than the configured maximum number of documents per block.

I'd be interested in evaluating what the compression ratio would be if we relaxed these conditions a bit, e.g. by allowing up to 5% dirtiness. My gut feeling is that the compression ratio could be barely worse while index-time CPU usage could be significantly improved.

---
Migrated from [LUCENE-10556](https://issues.apache.org/jira/browse/LUCENE-10556) by Adrien Grand (@jpountz), updated May 12 2022

**Comment by jpountz** [comment]
Updated numbers now that TMP no longer runs quadratic merges, and BEST_COMPRESSION:

|Dirtiness|Indexing time (msec)|
|-|-|
|0%|27219|
|1%|26897|
|5%|27196|
|20%|27043|
|33%|26188|
|50%|24729|
|75%|20993|
|100%|9971|

So the tolerable dirtiness doesn't affect indexing time too much unless unlimited (100%). My understanding is that because we merge 10 segments at once, an optimized merge typically increases dirtiness by 10x, so you need to bump the tolerable dirtiness very significantly to start seeing benefits. This benchmark suggests we wouldn't get very significant benefits from raising the maximum tolerable dirtiness.
