### ISSUE TITLE
Expand TieredMergePolicy deletePctAllowed limits

### ISSUE THREAD

**Issue by mdmarshmallow** [apache/lucene#11761]
### Description

I'm an engineer at Amazon Search and we have been experimenting with more aggressively getting rid of deleted documents. We use TieredMergePolicy and we would like to set `TieredMergePolicy#deletesPctAllowed` to be [lower than the current limit of 20%](https://github.com/apache/lucene/blob/main/lucene/core/src/java/org/apache/lucene/index/TieredMergePolicy.java#L157). 

I was wondering why this limit was set in place. I'm sure I could be missing some context here. Maybe we could keep the limits in place but allow users to explicitly remove the checks? Any information would be much appreciated, thanks!

**Comment by jpountz** [comment]
Historically this was not configurable and Lucene would allow up to 50% deleted documents. When we introduced an option, we made sure to introduce a lower bound on the value because a value of zero would essentially require Lucene to rewrite every segment that has a deletion after every update operation, which is certainly undesirable. Allowing users to go from 50% to 20% felt like a significant improvement already.

We could discuss lowering the limit if we feel like this could lead to merging patterns that are still acceptable. E.g. I used `BaseMergePolicyTestCase#doTestSimulateUpdates` in the past to get a sense of how this option would influence write amplification.

**Comment by mdmarshmallow** [comment]
Hi, thanks for the response! Your explanation of 0% not being allowed makes complete sense. For some context though, using our own forked version of `TieredMergePolicy`, we have tested with down to 2% allowable deletion and still see that behavior is desirable for us (more specifically much lower index sizes than at 20% deletes).

Maybe if we want to maintain those limits, we could create a `setDeletesPctAllowedUnsafe()` or something like that which has no limits on it (or at least drops the lower bound to being > 0 instead of > 20)?

**Comment by jpountz** [comment]
I got some numbers for write amplification for the case tested in `TestTieredMergePolicy#testSimulateUpdates`:

| Allowed percentage of deletes | Write amplification |
| ------------- | ------------- |
| 50 (max) | 4.34 |
| 33 (default) | 4.34 |
| 20 (min) | 4.68 |
| 10 | 6.13 |
| 5 | 8.76 |
| 4 | 10.31 |
| 3 | 12.97 |
| 2 | 18.76 |
| 1 | 37.89 |
| 0 | 10779.78 |

Assuming these numbers are representative, maybe we could allow users to configure 5% as the allowed percentage of deletes that their indexes may have, which translates to ~2x more write amplification compared to the default of 33% according to the above numbers.

For reference, the algorithm that `TieredMergePolicy` uses to keep the number of deletes under the threshold consists of running the most balanced merge (with a small bias towards merges that reclaim more deletes) until the number of deletes of the index is under the threshold.

**Comment by mdmarshmallow** [comment]
Thanks for taking the time to look into this! I think 5% would be a good start, it would be near the threshold we want to test (we were thinking 2% but looking at your initial write amplification numbers, this may not be a great idea). I'm also planning on making an issue to create a `FilterDirectory` that tracks the write amplification factor. This should let us (Amazon Search) get some write amplification numbers that I can hopefully share here as well.

**Comment by mdmarshmallow** [comment]
Here is the issue I created with a PR attached in case you were interested: https://github.com/apache/lucene/issues/11795

**Comment by dan2097** [comment]
I have also ran into this on our patent search system. In our index the problem is exagerrated by the larger documents tending to be more frequently reindexed so the 20% deleted documents can translate to 40% of the overall index size!
For my use case 5% would be a massive improvement.

I ccan definitely imagine that for a system where indexing is light and infrequent 2% may make sense to ensure optimal perfomance/disk usage, without requiring the explicit use expungeDeletes. Having said that 5% is definitely low enough for my use case.

**Comment by uschindler** [comment]
I was also doing consulting for an huge Elasticsearch user and they also had this problem of keeping deletes as low as possible and the 20% limit was way too high. 20% looks like an arbitrary limitation.

**Comment by jpountz** [comment]
If someone opens a PR to decrease the limit from 20% to 5% I'll happily approve the change given the results I shared above.

**Comment by mdmarshmallow** [comment]
Here is a PR: https://github.com/apache/lucene/pull/11831

**Comment by rmuir** [comment]
> I got some numbers for write amplification for the case tested in TestTieredMergePolicy#testSimulateUpdates:

@jpountz based on these numbers wouldn't it also make sense to consider changing the default from `33%` to `20%` as well? Just an idea.

**Comment by mdmarshmallow** [comment]
I can include that in the above PR as well if you all agree that it's a good idea.

**Comment by dan2097** [comment]
> I can include that in the above PR as well if you all agree that it's a good idea.

I think it's probably a good idea. Faster search performance (due to the indexes having fewer deleted documents) and a reduced risk of underestimating space requirements and running out of disk space seem a reasonable tradeoff for a small increase in indexing time.

**Comment by uschindler** [comment]
We didn't change the default for deletePctAllowed in the above PR only the lower limit. So if we are changing defaults maybe do this separately.

**Comment by jpountz** [comment]
+1 to update the default from 33 to 20.

**Comment by uschindler** [comment]
+1 to update the default from 33 to 20.

**Comment by mdmarshmallow** [comment]
I updated the PR to change the default as well.

**Comment by jpountz** [comment]
Closing: https://github.com/apache/lucene/pull/11831 has been merged.

**Comment by stefanvodita** [comment]
It's been a few years since this issue was created. In the meantime, we've successfully experimented with lower delete percentage thresholds for Amazon Product Search. Going from 5% to 2% has led to a significant improvement in search throughput, I think around 5% improvement on average. Given that positive result, I wonder if we can consider decreasing the bound more.

**Comment by jpountz** [comment]
I think I'd be ok with any lower bound that is strictly greater than 0. However, I am curious if the improvement that you are seeing is actually due to reducing the number of deletions, or if it is due to something else - for instance the index having fewer segments on average as a result of expunging deletes more aggressively.

In theory, going from 5% deletes to 2% deletes should bring an improvement of _at most_ 1-(100-2)/(100-5) ~=3%. The fact that you are seeing more may suggest that this speedup may be due to having fewer/bigger segments? If this is the case, then you should be able to get similar results by bumping the floor and max merged segment sizes?

**Comment by stefanvodita** [comment]
It's a good point @jpountz! Thank you also for the extra attention to TMP in #14823.
I've had a look at the Amazon Product Search indexes and confirmed that the deletes percentage does correlate with the number of segments and with performance.

Measurement is hard! To offer a more nuanced view, we've measured the impact of changing deletes percentage from 5% to 2% across different indexes and there is a lot of variation. I have numbers for two times we've tried this. Once, we measured an average improvement of 5% (I only had this measurement when I was talking about it in the previous comment), and the other time we measured 2.3% (this is more in line with the expected improvement).

**Comment by stefanvodita** [comment]
I recognise there is some ambiguity on how much of the performance improvement is due to the lowered deletes percentage, but I wanted to open a PR for it (#14893) in case we decide to go ahead with the decreased lower bound, and we can continue the conversation there if there are other factors to consider as well.
