### ISSUE TITLE
TestKnnVectorQuery.testScoreEuclidean fails

### ISSUE THREAD

**Issue by mayya-sharipova** [apache/lucene#11769]
### Description

Reproducibly fails on `main` branch.

### Gradle command to reproduce

./gradlew test --tests TestKnnVectorQuery.testScoreEuclidean -Dtests.seed=1DAEE5C9217129EB -Dtests.nightly=true -Dtests.locale=mas -Dtests.timezone=Africa/Libreville -Dtests.asserts=true -Dtests.file.encoding=UTF-8

**Comment by mayya-sharipova** [comment]
@msokolov I've noticed that in https://github.com/apache/lucene/pull/1054 we don't force merge index for this test anymore, and may end up with several segments, which leads to a test failure. Should we reintroduce force merge?

**Comment by msokolov** [comment]
sorry - did I break that? I think I replaced RandomIndexWriter with IndexWriter and took control over flushing and merging? But maybe I misremembered/messed up

**Comment by msokolov** [comment]
I believe https://github.com/apache/lucene/commit/e69c48b8d941f44bb73f0594b5f72947efe80948 should fix. I guess LuceneTestCase.newIndexWriterConfig can randomly commit, or result in unusual configs anyway. I don't think we want to forceMerge in this case because some of the test users of that method rely on document order.

**Comment by mayya-sharipova** [comment]
Thanks @msokolov.

I run the above test on main, and it doesn't fall anymore.
Closing the issue.

**Comment by msokolov** [comment]
I just backported to 9.x and 9_4 branches
