### ISSUE TITLE
Make NeighborArray fixed size

### ISSUE THREAD

**Issue by msokolov** [apache/lucene#11783]
### Description

Today we allow NeighborArray to grow dynamically, but we always allocate at its full size, and then grow it by 1 because when it is full-sized, we store a new neighbor at index *size* and then remove one of the neighbors based on a diversity criterion.  Instead, we might want to figure out how to do more efficient surgery on the array. But in the meantime, we could oversize the arrays by 1 from the start and then never change their size.

**Comment by jpountz** [comment]
I was surprised at how much space was saved by https://github.com/apache/lucene/pull/11860, which in-turn makes me wonder if the neighbor graphs are sparser than we think. If so, it may be a better idea to keep growing dynamically but set a much smaller initial size, in order to save on heap usage upon indexing and merging?
