### ISSUE TITLE
Customization of Edit distance costs for different operations

### ISSUE THREAD

**Issue by mohamedniyaz1996** [apache/lucene#11902]
### Description

I came across this python library [weighted-levenshtein](https://pypi.org/project/weighted-levenshtein/) which has a way to specify different costs for insertion, deletion, substitution and transposition operations. I did some research on Lucene-FuzzySearch looking for such support but couldn't find any.

Can we have this feature in upcoming releases? The impact will be huge incase of using Lucene for analysing keystroke errors on search-engine where all operation costs need not be 1. More details are provided on the above python-lib documentation.

Please let me know if this feature already exists in lucene so that I can close this request.

**Comment by tang-hi** [comment]
Lucene does not calculate the Levenshtein distance one by one. Instead, it precompiles the Levenshtein automaton based on your output, and then finds terms that meet the distance requirements. The state transitions of the Levenshtein automaton are also already hard-coded in the code.This is also why the maximum edit distance supported by Lucene is 2.
I think it would be difficult to support custom distances with different operation costs, because this would involve reworking the code related to the Levenshtein automaton.

If you're interested, you can check out the following resources.
[Blog](https://blog.mikemccandless.com/2011/03/lucenes-fuzzyquery-is-100-times-faster.html)

**Comment by mohamedniyaz1996** [comment]
@tang-hi , I agree it will be a dip in performance - but still it can be provided as a feature with a warning about performance drop.

**Comment by rmuir** [comment]
this would be far too trappy, entirely too slow. use toy python libraries like the one referenced if you want to build toys, but this is a library for building search engines
