### ISSUE TITLE
improve checkindex to be more thorough for vectors (e.g. test seeking)

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11911]
### Description

Currently checkindex only `next()'s` through the vectors. We should do some seeking as well. It doesnt have to be intense, e.g. we could do 64 seeks (if there's 20,000,000 docs in the index, seek to 0, 312500, ..., something like that).

This would have saved a lot of time with #11905 but will also improve testing in general. CheckIndex gets called on every index created by every test, so checks here are very powerful.

**Comment by jtibshirani** [comment]
This is a good idea! As a note -- in order to exercise all parts of the file format, we'll have to perform a kNN search too through `KnnVectorsReader#search`. If we only load `VectorValues` and iterating through them (even with skipping), then we won't exercise the HNSW graph part which lives in the `.vex` file.

**Comment by rmuir** [comment]
"read every byte of the index" is the promise that checkindex makes. So this bug is really important.
