### ISSUE TITLE
error-prone's JVM arguments need help

### ISSUE THREAD

**Issue by rmuir** [apache/lucene#11925]
### Description

error-prone runs extremely slowly because on an N-core computer, it spins up N/2 jvms, each one ergonomically sized for N as far as compiler threads etc. And it uselessly enables C2 compiler and G1 garbage collector.

when error-prone runs on my computer, the desktop gets unresponsive, can't navigate or click links or do anything else... it also has painfully slow execution due to these problems.

we need to pass this thing the usual stuff at least: `-XX:+UseParallelGC -XX:TieredStopAtLevel=1 -XX:ActiveProcessorCount=1`.

**Comment by rmuir** [comment]
I stared at https://github.com/tbroyer/gradle-errorprone-plugin/blob/main/src/main/kotlin/net/ltgt/gradle/errorprone/ErrorPronePlugin.kt but I couldnt figure out yet how to tweak this.

**Comment by dweiss** [comment]
I think you want to pass a jvm configuring flag to javac, assuming JavaCompile is in fork mode (which is always the case in Lucene). errorprone hacks into javac, so I think it'll work just fine. What this means is that you have to configure JavaCompile (like we do in other places) and pass "internal" options to it - this seems to work for me, for example:
```
javac -J-XX:ActiveProcessorCount=1 -J-XX:+PrintFlagsFinal --help
```

I'm not at my dev machine but I can try later.

**Comment by dweiss** [comment]
I think this is what you wanted, @rmuir 
https://github.com/apache/lucene/pull/11927

This tweaks jvm options of every javac task. I think the slowdown you're observing is not just because of jvm options but a side-effect of the fact that running with spotless triggers all of those javac tasks to be forked (they mess with bootclasspath, I think). By default javac runs in-process with gradle and this is faster on my machine (regardless of what jvm options I pass). If you take a peek at the patch, you can force everything to be forked but I'm not sure if it makes sense. 

Hope it helps!
