### ISSUE TITLE
LRUQueryCache disabled for indices with more than 33 segments

### ISSUE THREAD

**Issue by dnhatn** [apache/lucene#12140]
An Elasticsearch customer reported a search performance issue. We looked into the segment stats and found that the index has 34 * 5GB segments, and LRUQueryCache never cache these segments. The reason is that LRUQueryCache only caches segments that have [more than 3%](https://github.com/apache/lucene/blob/7baa01b3c2f93e6b172e986aac8ef577a87ebceb/lucene/core/src/java/org/apache/lucene/search/LRUQueryCache.java#L139-L148) of the total number of documents in the index, and all segments here have less than 3%.

I will work on the fix for this issue. Any suggestions are welcomed.

**Comment by rmuir** [comment]
or maybe use median instead of average to help prevent issues. then its guaranteed that biggest segments get cached.

**Comment by dnhatn** [comment]
@jpountz @rmuir Thank you for your suggestions. That means we only cache 17 out of 34 segments in this case. I wonder if we also cache segments that are greater than 95% of the median (or average) segment?

**Comment by jpountz** [comment]
I like medians better than averages in many cases, but would this require iterating over all segments in the index everytime we need to make a caching decision? I worry this could be a bottleneck for indexes with many segments and cheap queries. My reasoning for the average segment size was that it's something that can be computed cheaply as `topLevelReader.maxDoc() / leaves.size()`. To @dnhatn 's point, maybe it should even be half the average segment size to make sure it includes all segments from the upper tier? I'm going below 95% because I'd expect the next tier to have segments in the order of 10x smaller, so with a 50% threshold we'd cover segments from the upper tier with greater confidence while still excluding the next tier?

**Comment by dnhatn** [comment]
Thanks, Adrien. +1 to what you suggested.

@rmuir Are you okay with Adrien's proposal? If so, I can start working on the fix.

**Comment by rmuir** [comment]
> I like medians better than averages in many cases, but would this require iterating over all segments in the index everytime we need to make a caching decision? I worry this could be a bottleneck for indexes with many segments and cheap queries. My reasoning for the average segment size was that it's something that can be computed cheaply as `topLevelReader.maxDoc() / leaves.size()`.

If you have this problem then you have too many segments.

**Comment by rmuir** [comment]
> @rmuir Are you okay with Adrien's proposal? If so, I can start working on the fix.

I don't really care so much, but let's please not overengineer it and just keep it simple.
