### ISSUE TITLE
Update Lucene's NOTICE.txt to clarify what is ASL2 and what is CPL1

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12226]
### Description

Spinoff from [this discussion on java-user](https://lists.apache.org/thread/zg01tkq8wtmym27q3dolcg1msbtoxoxl):

There is confusion about why our `NOTICE.txt` for some modules (at least `lucene/queries`) references CPL1 (Common Public License 1.0) due to `junit` when we do not in fact redistribute `junit`.

IANAL so I'm not sure how to proceed on this.

**Comment by HoustonPutman** [comment]
I created a PR for this. According to Apache policy, when a release has a NOTICE.txt file, that file should only contain information on the source/binaries included in that release. Since JUnit is not a bundled dependency, it should not be included in the NOTICE.txt.

https://infra.apache.org/licensing-howto.html#bundled-vs-non-bundled
https://infra.apache.org/licensing-howto.html#mod-notice

I took some time to clean up other parts of the NOTICE.txt as well.
