### ISSUE TITLE
search.matchhighlight.TestPassageSelector.randomizedSanityCheck reproducible error

### ISSUE THREAD

**Issue by zhaih** [apache/lucene#12562]
### Description

Build: https://ci-builds.apache.org/job/Lucene/job/Lucene-Check-main/10242/

1 tests failed.
FAILED:  org.apache.lucene.search.matchhighlight.TestPassageSelector.randomizedSanityCheck

Error Message:
```
java.lang.AssertionError:
Expected: not a collection containing "><"
     but: was <[?, B'nE?
, ><, |u, $HX?Ox@, fV}?, ]ZR??x9]>

Stack Trace:
java.lang.AssertionError:
Expected: not a collection containing "><"
     but: was <[?, B'nE?
, ><, |u, $HX?Ox@, fV}?, ]ZR??x9]>
        at __randomizedtesting.SeedInfo.seed([BA589FCC77C2F999:4E6DB4BADBADAB93]:0)
        at org.hamcrest@2.2/org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest@2.2/org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
        at org.apache.lucene.search.matchhighlight.TestPassageSelector.randomizedSanityCheck(TestPassageSelector.java:350)
...
```

I can reproduce it on both main and branch_9x

### Gradle command to reproduce
```
./gradlew :lucene:highlighter:test --tests "org.apache.lucene.search.matchhighlight.TestPassageSelector.randomizedSanityCheck" -Ptests.jvms=4 -Ptests.haltonfailure=false -Ptests.jvmargs= -Ptests.seed=BA589FCC77C2F999 -Ptests.multiplier=2 -Ptests.gui=true -Ptests.file.encoding=ISO-8859-1
```

**Comment by dweiss** [comment]
Thanks @zhaih - this looks like something I wrote... I'll be taking a look on Monday, please feel free to leave it to me.

**Comment by dweiss** [comment]
Also, I'm not sure why the build indeed resulted in "build success" - will look into that as well,.
```
/home/jenkins/jenkins-slave/workspace/Lucene/Lucene-Check-main/gradlew -Dtests.haltonfailure=false -Dtests.badapples=false --continue check
```

**Comment by dweiss** [comment]
The "build success" here is caused by an explicit change made by Uwe, here: https://github.com/apache/lucene/issues/10513#issuecomment-1224072458

In his own words:

The tests.haltonfailure was added back, as it was heavily used by Jenkins. [...] Jenkins wants to differentiate between "build passed, but test failures" vs. "build did not pass due to compile failure, verifications". haltonfailure just reconfigures (like in ant) that the test runner does not exit the whole build with non-success exit code. Jenkins does not rely on exit code, it monitors test result xml files.

This makes sense in a CI world. Maybe we should omit printing this flag in the "reproduce with" line though. I'll file a separate issue for that.

**Comment by dweiss** [comment]
The issue is caused by random input clashing with test assertion, not a problem. I've filed PRs for both problems.
