### ISSUE TITLE
TestSizeBoundedForceMerge.testByteSizeLimit test failure

### ISSUE THREAD

**Issue by benwtrent** [apache/lucene#12648]
### Description

Came up in continuous testing. It has failed on 9x and main.

It replicates reliably.

```
org.apache.lucene.index.TestSizeBoundedForceMerge > testByteSizeLimit FAILED
    java.lang.AssertionError: expected:<3> but was:<5>
        at __randomizedtesting.SeedInfo.seed([AE91D9F034F31034:2DAA18CA35644BD5]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.apache.lucene.index.TestSizeBoundedForceMerge.testByteSizeLimit(TestSizeBoundedForceMerge.java:83)
```

### Gradle command to reproduce

./gradlew test --tests TestSizeBoundedForceMerge.testByteSizeLimit -Dtests.seed=AE91D9F034F31034 -Dtests.locale=no-NO -Dtests.timezone=America/Martinique -Dtests.asserts=true -Dtests.file.encoding=UTF-8

**Comment by benwtrent** [comment]
The replication has a `min` segment size of `695` in bytes. Running the test multiple times shows that it generally has a higher segment size of at least `699` when the test passes.

**Comment by jpountz** [comment]
I found the issue, this is due to codec randomization. This test fails when assigned the `SimpleText` codec and one of the segment IDs has the `\n` or `\` byte. This forces `SimpleText` to introduce an escape byte, which in-turn creates a segment which is one byte larger than some other segments and breaks some assumptions that the test is making. I'll open a PR shortly.
