### ISSUE TITLE
Optimize counts on 2-clauses disjunctions

### ISSUE THREAD

**Issue by jpountz** [apache/lucene#12644]
### Description

Counts on disjunctions could be optimized in the following case:
 - 2 clauses
 - both clauses are term queries
 - there are no deletes

Then we could compute the count as `count(clause1) + count(clause2) - count(clause1 AND clause2)` which almost certainly runs faster.

If we do that we'll probably want to update nightly benchmarks to either have deletes or add tasks on disjunctions of 3 terms or more to retain coverage on actual disjunction counts.

**Comment by gsmiller** [comment]
Oh, +1. Interesting idea to try out!

**Comment by dweiss** [comment]
You should include a venn diagram for this - so classic. :)

I suspect you want to use a stored count for getting count(clauseX), right? Because there's technically nothing preventing this from working with deleted documents if you apply deletions to each of the components - this wasn't clear to me from the description at first glance.

**Comment by jpountz** [comment]
You are right, I added the condition on deleted docs and term queries so that `count(clause)` can be computed as the doc freq of the term.

**Comment by jpountz** [comment]
Adressed via https://github.com/apache/lucene/pull/13036.
