### ISSUE TITLE
Don't provide two ways to build an FST

### ISSUE THREAD

**Issue by mikemccand** [apache/lucene#12695]
### Description

Spinoff from [this great comment](https://github.com/apache/lucene/pull/12633#discussion_r1360866889):

Today, you can build an FST either using `FSTCompiler.Builder` or the two-parameter `FSTCompiler` ctor.

Should we remove the latter and expose only the Builder?

**Comment by cavorite** [comment]
I'm be willing to work on this issues (as a way to get more familiar with Lucene's internal code base). First, I'd like to see if I'm understanding the work needed. 

So far, it seems that the refactoring is relatively straightforward to do: replace the invocations of the constructor of `FSTCompiler` by creating an instance of `Builder` and then calling the `build()` method.  For instance, replacing the line:

```
FSTCompiler<BytesRef> fstCompiler = new FSTCompiler<>(FST.INPUT_TYPE.BYTE4, outputs);
```

by this one:

```
FSTCompiler<BytesRef> fstCompiler = new FSTCompiler.Builder<>(FST.INPUT_TYPE.BYTE4, outputs).build();
```

There are about 40 usages of the constructor in the repositoy (including modules other than `core`), so we need to replace the usages in all of them and also mark the constructor as deprecated (so that it can be deleted in an upcoming major release).

Would that be all what's necessary for this issue?

**Comment by mikemccand** [comment]
Yes that's exactly the idea!  Thank you @cavorite for tackling this.

**Comment by mikemccand** [comment]
Backported to 9.9.0 -- closing.  Thank you @cavorite!
