### ISSUE TITLE
Backout changes messing around with fieldinfos on merge

### ISSUE THREAD

**Issue by ChrisHegarty** [apache/lucene#13809]
This meta issue has been filed to accumulate and track issues that need to be backed out because they're messing around with fieldinfos on merge. Changes that should be reverted:

- [ ]:  #13686
- [ ]: ...

relates #13805, #13807, #13808

**Comment by ChrisHegarty** [comment]
@benwtrent @rmuir @jpountz   if you are aware of any other changes that need to be backed out, can you please add them to the above description. Thank you.

**Comment by benwtrent** [comment]
Ah, the other one I was thinking of is this one: https://github.com/apache/lucene/pull/13763

Which isn't merged. So, it might only be the doc values one.

**Comment by rmuir** [comment]
+1 to back any and all optimizations out that are based on field numbers at merge, esp discovering problems right before a release.

the problem with mixed-up field numbers:
* it causes silent corruption to the end-user during merge (data gets mixed up)
* testing for the bugs is not good enough (the failing dv-vs-storedfields tests are especially gnarly and they only barely caught it after many iterations)
* impacts every part of index, including ones that don't today have crazy tests like dv-vs-storedfields.

Separately i think we should also improve the testing too per @jpountz PR. optimizations like this need a baking time because the tests are currently too weak for them.

**Comment by bugmakerrrrrr** [comment]
> Ah, the other one I was thinking of is this one: #13763

When we get the knn values, we resolve the field info according to the ReadState used to construct the KnnReader. Therefore, I think this shouldn't mess up the field infos.

**Comment by jpountz** [comment]
OK. Let's revert now, and try to add them back after branch_10_0 is cut, so that we can have a long backing period with the new tests before these optimizations get released.
