### ISSUE TITLE
How to use hnsw int4 when loading index

### ISSUE THREAD

**Issue by hanqiushi** [apache/lucene#13921]
### Description

Hi, I have a question when using hnsw int4.
I have built an index using Lucene99HnswScalarQuantizedVectorsFormat bits=4 param. But I don't know how to use it in search.
I have code below to load index:

            Directory directory = FSDirectory.open(indexPath);
            IndexReader reader = DirectoryReader.open(directory);

I don't know how to pass bits=4 param when loading index or when searching, the code runs with default value bits=7 and the results are not correct. 

So how to use int4 in code when loading or searching? Thanks for your answer

**Comment by benwtrent** [comment]
@hanqiushi you don't need to do anything special. Since its a format, you only have to query the index. 

So, once you have indexed a bunch of [KnnFloatVectorField](https://lucene.apache.org/core/9_12_0/core/org/apache/lucene/document/KnnFloatVectorField.html), you can just search them with a [KnnFloatVectorQuery](https://lucene.apache.org/core/9_12_0/core/org/apache/lucene/search/KnnFloatVectorQuery.html). 

Example:

```
try (IndexReader reader = DirectoryReader.open(dir)) {
  IndexSearcher searcher = new IndexSearcher(reader);
   TopDocs topDocs = searcher.search(new KnnFloatVectorQuery(
    KNN_VECTOR_FIELD, // the field name.
    queryVector, // the float query vector, dims must be the same as the indexed fields
    k), // the `k` to search for, could be considered efSearch
    k); // how many docs to return
```

Some other tips:

 - Use `confidence_interval=0` in the format, this greatly improves `int4` quality.
 - Pass `compress=true` as well or you will not gain the memory advantages. 
SEE: https://lucene.apache.org/core/9_12_0/core/org/apache/lucene/codecs/lucene99/Lucene99HnswScalarQuantizedVectorsFormat.html#%3Cinit%3E(int,int,int,int,boolean,java.lang.Float,java.util.concurrent.ExecutorService)
