### ISSUE TITLE
Null value dereference [LUCENE-6663]

### ISSUE THREAD

**Issue by asfimport** [apache/lucene#7721]
Found several cases of potential null dereference. Creating a single patch as suggested to fix them.

---
Migrated from [LUCENE-6663](https://issues.apache.org/jira/browse/LUCENE-6663) by Rishabh Patel, updated May 09 2016
Attachments: [LUCENE-6663.patch](https://apache.github.io/lucene-jira-archive/attachments/LUCENE-6663/LUCENE-6663.patch)

**Comment by slow-J** [comment]
The patch would still apply now if the files were in the same directory.... Will put this forward in a PR and see should we still merge it? What is the best way to give credit to Rishabh, the Changes.txt entry?

**Comment by msokolov** [comment]
If this has been open for 8 years, yet we have never had an NPE resulting from missing these checks, then I think we can concluded the checks are not needed. As a rule, we only need null checks where we expect null values. If we get an unexpected null value, we *want* an unexpected exception so we can find the root cause. So I don't think we should merge this.

**Comment by slow-J** [comment]
> If this has been open for 8 years, yet we have never had an NPE resulting from missing these checks, then I think we can concluded the checks are not needed. As a rule, we only need null checks where we expect null values. If we get an unexpected null value, we _want_ an unexpected exception so we can find the root cause. So I don't think we should merge this.

Thanks for the info @msokolov, that makes sense! If we close this issue, I can cancel the PR.

**Comment by msokolov** [comment]
thanks for the ping, I explained why we won't do this above
